# Generated by Django 5.0.1 on 2024-01-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_company_name', models.CharField(max_length=256, verbose_name='Юридическое наименование')),
                ('field_of_activity', models.CharField(max_length=128, verbose_name='Сфера деятельности')),
                ('type_of_business', models.CharField(max_length=128, verbose_name='Тип бизнеса')),
                ('bin_number', models.IntegerField(max_length=12, verbose_name='БИН')),
                ('bik_number', models.CharField(max_length=10, verbose_name='БИК')),
                ('bank_name', models.CharField(max_length=128, verbose_name='Банк')),
                ('iban_number', models.CharField(max_length=34, verbose_name='ИИК (номер счёта)')),
                ('legal_company_address', models.CharField(max_length=256, verbose_name='Юридический адрес ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Данные компании',
            },
        ),
    ]
