# Generated by Django 5.0.1 on 2024-01-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bin_number',
            field=models.CharField(max_length=12, verbose_name='БИН'),
        ),
    ]
